apiVersion: v1
kind: Pod                                            
metadata:
  name: sa-frontend2
  labels:
    app: sa-frontend      # The only change
spec:                                                
  containers:
    - image: rinormaloku/sentiment-analysis-frontend 
      name: sa-frontend                              
      ports:
        - containerPort: 80